### ISSUE TITLE
调低弹幕伤害

### ISSUE THREAD

**Issue by YujiaSanhu** [Crystal1921/LivelyDanmaku#1]
作者您好,我想请问该如何调整弹幕的伤害直?
目前和朋友联机但弹幕伤害过高,碰到怪物基本是一击必命,想稍微调低弹幕造成伤害

**Comment by YujiaSanhu** [comment]
更:

实测在单人下，弹幕伤害是2点；
但是在服务器里会变成185点

**Comment by YujiaSanhu** [comment]
二更:

在单人实验下,我发现当玩家用传送的方式随机传送至某地时，弹幕伤害会显著翻倍(一击必杀
但若玩家全程用飞或徒步走时,弹幕伤害都是一直维持正常

**Comment by Crystal1921** [comment]
奇怪，可能是伤害有地方写糠了。
晚上看一眼）

**Comment by Crystal1921** [comment]
泪目了，这里都有一年没动过了，竟然还有人能发issue

**Comment by YujiaSanhu** [comment]
TeaCon 甲辰看到后就一直在玩,这类型的mod极度稀少,刚好跟朋友开东方服务器玩就顺便研究一下伤害

目前已知瞬间传送会造成DPS累加，最后打出去伤害超超级高
![Uploading 2024-09-17_17.53.00.png…]()

**Comment by YujiaSanhu** [comment]
TeaCon 甲辰看到后就一直在玩,这类型的mod极度稀少,刚好跟朋友开东方服务器玩就顺便研究一下伤害

目前已知瞬间传送会造成DPS累加，最后打出去伤害超超级高

![2024-09-17_17 53 00](https://github.com/user-attachments/assets/cf18d78d-11a2-4403-9815-45a31c5edf32)
![2024-09-17_17 56 43](https://github.com/user-attachments/assets/76189990-b767-4724-a265-7c34f7112d3e)

**Comment by Crystal1921** [comment]
![屏幕截图 2024-09-18 122747](https://github.com/user-attachments/assets/9068ca50-6154-421d-979b-16f3f47ba177)
怪了，我本地开服测试没问题

**Comment by Crystal1921** [comment]
没事，等今年TeaCon结束了，有空闲就准备换成lcy0x1的[DanmakuAPI](https://github.com/Minecraft-LightLand/DanmakuAPI)

**Comment by Crystal1921** [comment]
跟妖怪的归家同款的那个（

**Comment by banana190** [comment]
src/main/java/com/tutorial/lively_danmaku/entity/com.tutorial.lively_danmaku.entity/AbstractDanmaku.java line:44

        float i = (float) (Math.sqrt(this.distanceToSqr(this.getDeltaMovement())) / 20);

我不知道原本想要的效果是啥，但是你把投射物的座標(x1 y1 z1)對投射物的速度向量(x'1 y'1 z'1)取了平方距離

而非與目標物的座標(x2 y2 z2)進行計算

所以當投射物距離0 0 0越遠時，彈幕的傷害會是 "距離(0,0,0)/20"

**Comment by Crystal1921** [comment]
嘶，坏坏坏，我憨了

**Comment by Crystal1921** [comment]
等今年TeaCon结束了有时间整个翻修一下

**Comment by banana190** [comment]
就不知道你本來傷害想怎麼設計，所以不知道現在怎麼改給群內用 

我順便修了一下那啥
src/main/java/com/tutorial/lively_danmaku/event/SizeChangeEvent.java line:19

            boolean isReimuHeaddress = event.getTo().is(ItemRegistry.ReimuHeaddress.get());

LivingEquipmentChangeEvent 不只會偵測裝備變更，手上的道具欄變更也會進行偵測

所以一切道具就會抓到不是髮帶的東西

直接改成跟下面碰裝箱判定一樣的機制就行

            boolean isReimuHeaddress = player.getInventory().getArmor(3).is(ItemRegistry.ReimuHeaddress.get());

這樣切換道具就不會墜機了
