### ISSUE TITLE
Jukeboxes do not work when lively_danmaku is enabled | lively_danmaku が有効になっている場合、ジュークボックスが機能しません

### ISSUE THREAD

**Issue by PwRhGaStPY** [Crystal1921/LivelyDanmaku#2]
Minecraft 1.20.1 
Forge 47.3.0 
[lively_danmaku 1.3.1](https://modrinth.com/mod/livelydanmaku/version/1.3.1) 

https://github.com/user-attachments/assets/ba28f76f-a4d0-48af-a08b-3dba73c7850c

https://mclo.gs/y3HBdcr 

I don't know Japanese, so I'm using machine translation. I apologize for any errors or misunderstandings. 
日本語がわからないので機械翻訳を使っています。間違いや誤解があった場合はお詫び申し上げます。

**Comment by Crystal1921** [comment]
This is my mistake, I'll fix it

**Comment by Crystal1921** [comment]
Have fixed in https://github.com/Crystal1921/LivelyDanmaku/commit/9b246a64cb9a9b93e4b25374c570e781f89e63c8
